import calci_module
print("Enter two numbers:  ")
x,y=map(int,input().split())
res1=calci_module.add(x,y)
res2=calci_module.multiply(x,y)
res3=calci_module.substract(x,y)
res4=calci_module.divisible(x,y)
res5=calci_module.floatdivision(x,y)
res6=calci_module.modulerdiv(x,y)
print("Sum :",res1)
print("Product: ",res2)
print("Substract : ",res3)
print("Division : ",res4)
print("Float Division: ",res5)
print("Modulas : ",res6)
